name: Build (for test)

on:
  push:
    branches:
      - develop-mame
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: corepack enable
    - run: npm install
    - run: cp config.example.json config.json
    - name: Build
      run: npm run build
